/* oxlint-disable react/only-export-components */
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type PropsWithChildren } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'

export type Language = 'en' | 'ka' | 'ru'

export const languages: { code: Language; short: string; label: string }[] = [
  { code: 'en', short: 'EN', label: 'English' },
  { code: 'ka', short: 'KA', label: 'ქართული' },
  { code: 'ru', short: 'RU', label: 'Русский' },
]

const copy: Record<string, Partial<Record<Language, string>>> = {
  'Solutions': { ka: 'გადაწყვეტილებები', ru: 'Решения' }, 'Work': { ka: 'ნამუშევრები', ru: 'Работы' }, 'Process': { ka: 'პროცესი', ru: 'Процесс' }, 'Pricing': { ka: 'ფასები', ru: 'Цены' }, 'About': { ka: 'ჩვენ შესახებ', ru: 'О нас' },
  'Menu': { ka: 'მენიუ', ru: 'Меню' }, 'Close': { ka: 'დახურვა', ru: 'Закрыть' }, 'Main navigation': { ka: 'მთავარი ნავიგაცია', ru: 'Главная навигация' }, 'Salyior home': { ka: 'Salyior-ის მთავარი გვერდი', ru: 'Главная Salyior' },
  'Let’s talk': { ka: 'დაგვიკავშირდით', ru: 'Обсудить проект' }, 'Start a project': { ka: 'დაიწყეთ პროექტი', ru: 'Начать проект' }, 'Skip to content': { ka: 'შინაარსზე გადასვლა', ru: 'Перейти к содержанию' },
  'WHAT CAN WE BUILD FOR YOU?': { ka: 'რა შეგვიძლია შეგიქმნათ?', ru: 'ЧТО МЫ МОЖЕМ СОЗДАТЬ?' }, 'Websites': { ka: 'ვებსაიტები', ru: 'Сайты' }, 'Web apps': { ka: 'ვებაპლიკაციები', ru: 'Веб-приложения' }, 'SEO & performance': { ka: 'SEO და სისწრაფე', ru: 'SEO и скорость' }, 'Bookings & integrations': { ka: 'ჯავშნები და ინტეგრაციები', ru: 'Бронирование и интеграции' },
  'A better home for your business.': { ka: 'უკეთესი ონლაინ სივრცე თქვენი ბიზნესისთვის.', ru: 'Лучшее онлайн-пространство для вашего бизнеса.' }, 'Useful tools, built around you.': { ka: 'თქვენზე მორგებული სასარგებლო ხელსაწყოები.', ru: 'Полезные инструменты под ваши задачи.' }, 'Get found. Load fast.': { ka: 'იყავით ხილული. ჩაიტვირთეთ სწრაფად.', ru: 'Будьте заметны. Загружайтесь быстро.' }, 'Make the next step effortless.': { ka: 'შემდეგი ნაბიჯი გახადეთ მარტივი.', ru: 'Сделайте следующий шаг простым.' }, 'Explore all solutions': { ka: 'ყველა გადაწყვეტილება', ru: 'Все решения' },
  'Thoughtful websites.': { ka: 'გააზრებული ვებსაიტები.', ru: 'Продуманные сайты.' }, 'Built for your next customer.': { ka: 'შექმნილი თქვენი შემდეგი მომხმარებლისთვის.', ru: 'Созданные для вашего следующего клиента.' }, 'Independent studio · Georgia': { ka: 'დამოუკიდებელი სტუდია · საქართველო', ru: 'Независимая студия · Грузия' }, 'Explore': { ka: 'აღმოაჩინეთ', ru: 'Разделы' }, 'The studio': { ka: 'სტუდია', ru: 'Студия' }, 'About Salyior': { ka: 'Salyior-ის შესახებ', ru: 'О Salyior' }, 'Pricing & scope': { ka: 'ფასი და მოცულობა', ru: 'Цены и объём' }, 'Free website review': { ka: 'ვებსაიტის უფასო შეფასება', ru: 'Бесплатный разбор сайта' }, 'Let’s connect': { ka: 'დავუკავშირდეთ', ru: 'Связаться' }, 'Arrange a call': { ka: 'დაგეგმეთ ზარი', ru: 'Назначить звонок' }, 'All rights reserved.': { ka: 'ყველა უფლება დაცულია.', ru: 'Все права защищены.' }, 'Batumi, Tbilisi & across Georgia': { ka: 'ბათუმი, თბილისი და მთელი საქართველო', ru: 'Батуми, Тбилиси и вся Грузия' }, 'Privacy': { ka: 'კონფიდენციალურობა', ru: 'Конфиденциальность' },
  'A conversation is a good start': { ka: 'საუბარი კარგი დასაწყისია', ru: 'Разговор — хорошее начало' }, 'Good things begin': { ka: 'კარგი საქმე იწყება', ru: 'Хорошее начинается' }, 'with a hello.': { ka: 'ერთი გამარჯობით.', ru: 'с простого приветствия.' }, 'Let’s find a time.': { ka: 'შევარჩიოთ დრო.', ru: 'Подберём время.' }, 'A fresh pair of eyes.': { ka: 'ახალი ხედვა.', ru: 'Свежий взгляд.' }, 'Tell us what’s next.': { ka: 'გვიამბეთ თქვენი იდეის შესახებ.', ru: 'Расскажите, что дальше.' },
  'A relaxed conversation about your business and what a website could do for it.': { ka: 'მშვიდი საუბარი თქვენს ბიზნესზე და იმაზე, თუ რას მოუტანს მას კარგი ვებსაიტი.', ru: 'Спокойный разговор о вашем бизнесе и о том, что может дать ему хороший сайт.' }, 'Share your website or social page. We’ll look for opportunities to improve it.': { ka: 'გამოგვიგზავნეთ ვებსაიტი ან სოციალური გვერდი და ვიპოვით გაუმჯობესების შესაძლებლობებს.', ru: 'Пришлите сайт или страницу в соцсети — мы найдём возможности для улучшения.' }, 'A new website, a fresh direction, or just a question. We’d love to hear it.': { ka: 'ახალი ვებსაიტი, ახალი მიმართულება ან უბრალოდ კითხვა — სიამოვნებით მოგისმენთ.', ru: 'Новый сайт, новое направление или просто вопрос — будем рады обсудить.' },
  'You’ll speak with David.': { ka: 'თქვენ დავითს ესაუბრებით.', ru: 'Вы будете общаться с Давидом.' }, 'Founder, designer & developer': { ka: 'დამფუძნებელი, დიზაინერი და დეველოპერი', ru: 'Основатель, дизайнер и разработчик' }, 'Prefer to write about a project?': { ka: 'გირჩევნიათ პროექტზე მოგვწეროთ?', ru: 'Предпочитаете написать о проекте?' }, 'Prefer a call? Let’s arrange one.': { ka: 'გირჩევნიათ ზარი? დავგეგმოთ.', ru: 'Предпочитаете звонок? Давайте назначим.' }, 'Clear advice': { ka: 'მკაფიო რჩევა', ru: 'Понятная консультация' }, 'No obligation': { ka: 'ვალდებულების გარეშე', ru: 'Без обязательств' },
  'Direct contact options': { ka: 'პირდაპირი კონტაქტის გზები', ru: 'Способы прямой связи' }, 'Call': { ka: 'დარეკვა', ru: 'Позвонить' }, 'Message David': { ka: 'მისწერეთ დავითს', ru: 'Написать Давиду' },
  'Thank you, we have it.': { ka: 'გმადლობთ, მივიღეთ.', ru: 'Спасибо, мы получили сообщение.' }, 'David will review your message and get back to you.': { ka: 'დავითი გაეცნობა შეტყობინებას და დაგიკავშირდებათ.', ru: 'Давид прочитает сообщение и свяжется с вами.' }, 'Send another message': { ka: 'სხვა შეტყობინების გაგზავნა', ru: 'Отправить ещё сообщение' }, 'ARRANGE A CALL': { ka: 'ზარის დაგეგმვა', ru: 'НАЗНАЧИТЬ ЗВОНОК' }, 'WEBSITE REVIEW': { ka: 'ვებსაიტის შეფასება', ru: 'РАЗБОР САЙТА' }, 'YOUR NEXT PROJECT': { ka: 'თქვენი შემდეგი პროექტი', ru: 'ВАШ НОВЫЙ ПРОЕКТ' }, 'HELLO': { ka: 'გამარჯობა', ru: 'ЗНАКОМСТВО' },
  'Your name': { ka: 'თქვენი სახელი', ru: 'Ваше имя' }, 'How should we call you?': { ka: 'როგორ მოგმართოთ?', ru: 'Как к вам обращаться?' }, 'Email address': { ka: 'ელფოსტა', ru: 'Электронная почта' }, 'Business or website': { ka: 'ბიზნესი ან ვებსაიტი', ru: 'Бизнес или сайт' }, 'Optional': { ka: 'არასავალდებულო', ru: 'Необязательно' }, 'Your business name or current website': { ka: 'ბიზნესის სახელი ან არსებული ვებსაიტი', ru: 'Название бизнеса или текущий сайт' }, 'A convenient time': { ka: 'სასურველი დრო', ru: 'Удобное время' }, 'Day, time and timezone — we’ll confirm together': { ka: 'დღე, დრო და დროის სარტყელი — ერთად დავადასტურებთ', ru: 'День, время и часовой пояс — подтвердим вместе' }, 'What would you like to discuss?': { ka: 'რის განხილვას ისურვებდით?', ru: 'Что вы хотите обсудить?' }, 'What do you have in mind?': { ka: 'რა გაქვთ ჩაფიქრებული?', ru: 'Что вы задумали?' }, 'Your website link and anything you’d like us to look at…': { ka: 'ვებსაიტის ბმული და საკითხები, რომელთა შეფასებაც გსურთ…', ru: 'Ссылка на сайт и всё, что вы хотите проверить…' }, 'A little about your business and what you’re hoping for…': { ka: 'ცოტა რამ თქვენს ბიზნესზე და სასურველ შედეგზე…', ru: 'Немного о вашем бизнесе и желаемом результате…' }, 'Leave this empty': { ka: 'დატოვეთ ცარიელი', ru: 'Оставьте пустым' }, 'Sending…': { ka: 'იგზავნება…', ru: 'Отправка…' }, 'Continue in email': { ka: 'ელფოსტაში გაგრძელება', ru: 'Продолжить в почте' }, 'Request a call': { ka: 'ზარის მოთხოვნა', ru: 'Запросить звонок' }, 'Send your enquiry': { ka: 'მოთხოვნის გაგზავნა', ru: 'Отправить запрос' }, 'Opens an email draft for you to review and send.': { ka: 'გაიხსნება ელფოსტის მონახაზი, რომელსაც გადაამოწმებთ და გააგზავნით.', ru: 'Откроется черновик письма, который можно проверить и отправить.' }, 'Your details stay between us. Used to respond to your enquiry.': { ka: 'თქვენი მონაცემები კონფიდენციალურია და გამოიყენება მხოლოდ პასუხისთვის.', ru: 'Ваши данные конфиденциальны и используются только для ответа.' }, 'Open email draft': { ka: 'ელფოსტის მონახაზის გახსნა', ru: 'Открыть черновик' },
  'Your next chapter': { ka: 'თქვენი შემდეგი ეტაპი', ru: 'Ваш следующий этап' }, 'Let’s make it': { ka: 'ერთად', ru: 'Давайте это' }, 'happen.': { ka: 'შევქმნათ.', ru: 'реализуем.' }, 'Start a conversation': { ka: 'დაიწყეთ საუბარი', ru: 'Начать разговор' },
  'Independent web studio · Batumi, Georgia': { ka: 'დამოუკიდებელი ვებსტუდია · ბათუმი, საქართველო', ru: 'Независимая веб-студия · Батуми, Грузия' }, 'Built to impress.': { ka: 'შექმნილი შთაბეჭდილებისთვის.', ru: 'Создано впечатлять.' }, 'Designed for': { ka: 'დიზაინი ახალი', ru: 'Создано для' }, 'new enquiries.': { ka: 'მომართვებისთვის.', ru: 'новых заявок.' }, 'Websites and web applications for businesses in Batumi, Tbilisi and across Georgia—built to be found and turn visits into enquiries.': { ka: 'ვებსაიტები და ვებაპლიკაციები ბათუმის, თბილისის და მთელი საქართველოს ბიზნესებისთვის — საძიებო სისტემებში ხილვადობისა და ახალი მომართვებისთვის.', ru: 'Сайты и веб-приложения для бизнеса в Батуми, Тбилиси и по всей Грузии — чтобы вас находили и обращались к вам.' }, 'Let’s build your website': { ka: 'შევქმნათ თქვენი ვებსაიტი', ru: 'Создадим ваш сайт' }, 'Clear scope. Direct contact. No pressure.': { ka: 'მკაფიო მოცულობა. პირდაპირი კონტაქტი. ზეწოლის გარეშე.', ru: 'Понятный объём. Прямой контакт. Без давления.' }, 'A LITTLE OF WHAT WE DO': { ka: 'ჩვენი ნამუშევრების მცირე ნაწილი', ru: 'НЕМНОГО О НАШЕЙ РАБОТЕ' }, 'Real estate': { ka: 'უძრავი ქონება', ru: 'Недвижимость' }, 'Independent build': { ka: 'დამოუკიდებელი პროექტი', ru: 'Независимый проект' }, 'View all work': { ka: 'ყველა ნამუშევარი', ru: 'Все работы' }, 'Every detail has a job.': { ka: 'ყველა დეტალს აქვს მიზანი.', ru: 'У каждой детали есть задача.' }, 'Design': { ka: 'დიზაინი', ru: 'Дизайн' }, 'Performance': { ka: 'სისწრაფე', ru: 'Скорость' }, 'Enquiries': { ka: 'მომართვები', ru: 'Заявки' },
  'Selected work': { ka: 'შერჩეული ნამუშევრები', ru: 'Избранные работы' }, 'Different worlds.': { ka: 'სხვადასხვა სფერო.', ru: 'Разные сферы.' }, 'The same care.': { ka: 'ერთნაირი ზრუნვა.', ru: 'Одинаковая забота.' }, 'Explore all projects': { ka: 'ყველა პროექტი', ru: 'Все проекты' }, 'A website with a purpose': { ka: 'მიზანმიმართული ვებსაიტი', ru: 'Сайт с целью' }, 'Good looks.': { ka: 'ლამაზი იერი.', ru: 'Красивый вид.' }, 'Better foundations.': { ka: 'ძლიერი საფუძველი.', ru: 'Сильная основа.' }, 'Help the right people find you, understand your offer and take the next step.': { ka: 'დაეხმარეთ სწორ ადამიანებს გიპოვონ, გაიგონ თქვენი შეთავაზება და გადადგან შემდეგი ნაბიჯი.', ru: 'Помогите нужным людям найти вас, понять предложение и сделать следующий шаг.' }, 'Explore our solutions': { ka: 'ჩვენი გადაწყვეტილებები', ru: 'Наши решения' }, 'Simple from the start': { ka: 'მარტივი დასაწყისიდანვე', ru: 'Просто с самого начала' }, 'Your idea. Our expertise.': { ka: 'თქვენი იდეა. ჩვენი გამოცდილება.', ru: 'Ваша идея. Наш опыт.' }, 'A clear way forward.': { ka: 'მკაფიო გზა წინ.', ru: 'Понятный путь вперёд.' }, 'We agree the scope, create your design and bring it to life—with you involved along the way.': { ka: 'ვათანხმებთ მოცულობას, ვქმნით დიზაინს და ვაცოცხლებთ მას — თქვენი მონაწილეობით ყველა ეტაპზე.', ru: 'Согласуем объём, создаём дизайн и воплощаем его — с вашим участием на каждом этапе.' }, 'How we work': { ka: 'როგორ ვმუშაობთ', ru: 'Как мы работаем' },
  'The portfolio': { ka: 'პორტფოლიო', ru: 'Портфолио' }, 'Work with character.': { ka: 'ხასიათიანი ნამუშევრები.', ru: 'Работы с характером.' }, 'Built with purpose.': { ka: 'შექმნილი მიზნით.', ru: 'Созданные с целью.' }, 'Client work, independent builds and design explorations. Each with a business and an audience in mind.': { ka: 'კლიენტების პროექტები, დამოუკიდებელი ნამუშევრები და დიზაინის კვლევები — თითოეული ბიზნესისა და აუდიტორიის გათვალისწინებით.', ru: 'Клиентские проекты, независимые работы и дизайн-эксперименты — каждый с учётом бизнеса и аудитории.' }, 'ALL PROJECTS': { ka: 'ყველა პროექტი', ru: 'ВСЕ ПРОЕКТЫ' }, 'SELECTED EXPERIENCES': { ka: 'შერჩეული გამოცდილება', ru: 'ИЗБРАННЫХ ПРОЕКТОВ' }, 'All work': { ka: 'ყველა ნამუშევარი', ru: 'Все работы' }, 'The approach': { ka: 'მიდგომა', ru: 'Подход' }, 'A closer look.': { ka: 'უფრო ახლოდან.', ru: 'Подробнее.' }, 'Visit website': { ka: 'ვებსაიტის ნახვა', ru: 'Открыть сайт' }, 'In the experience': { ka: 'გამოცდილებაში', ru: 'В проекте' },
  'More than a website.': { ka: 'ვებსაიტზე მეტი.', ru: 'Больше, чем сайт.' }, 'A way to move forward.': { ka: 'განვითარების გზა.', ru: 'Путь вперёд.' }, 'Design, discovery and practical features, built around your next customer.': { ka: 'დიზაინი, ხილვადობა და პრაქტიკული ფუნქციები თქვენი შემდეგი მომხმარებლის გარშემო.', ru: 'Дизайн, заметность и полезные функции для вашего следующего клиента.' },
  'The process': { ka: 'პროცესი', ru: 'Процесс' }, 'No guesswork.': { ka: 'ვარაუდების გარეშე.', ru: 'Без догадок.' }, 'Just good collaboration.': { ka: 'მხოლოდ კარგი თანამშრომლობა.', ru: 'Только хорошая работа вместе.' }, 'One partner and a clear next step, from the first hello to the final handover.': { ka: 'ერთი პარტნიორი და მკაფიო შემდეგი ნაბიჯი — პირველი საუბრიდან საბოლოო ჩაბარებამდე.', ru: 'Один партнёр и понятный следующий шаг — от первого разговора до передачи проекта.' },
  'The right website.': { ka: 'სწორი ვებსაიტი.', ru: 'Подходящий сайт.' }, 'A clear starting point.': { ka: 'მკაფიო დასაწყისი.', ru: 'Понятная отправная точка.' }, 'Choose the kind of website you need. We’ll shape the scope and quote around your business.': { ka: 'აირჩიეთ საჭირო ტიპის ვებსაიტი და ჩვენ თქვენს ბიზნესზე მოვარგებთ მოცულობასა და ფასს.', ru: 'Выберите нужный тип сайта, а мы подберём объём и стоимость под ваш бизнес.' }, 'A GOOD FIT FOR': { ka: 'კარგად შეეფერება', ru: 'ПОДХОДИТ ДЛЯ' }, 'Discuss this website': { ka: 'განვიხილოთ ეს ვებსაიტი', ru: 'Обсудить этот сайт' }, 'A written scope and agreed price before work begins. Additional services and ongoing costs are discussed upfront.': { ka: 'სამუშაოს დაწყებამდე მიიღებთ წერილობით მოცულობასა და შეთანხმებულ ფასს. დამატებითი მომსახურება წინასწარ განიხილება.', ru: 'До начала работ вы получите письменный объём и согласованную цену. Дополнительные услуги обсуждаются заранее.' }, 'Before we begin': { ka: 'დაწყებამდე', ru: 'Перед началом' }, 'A few useful': { ka: 'რამდენიმე სასარგებლო', ru: 'Несколько полезных' }, 'answers.': { ka: 'პასუხი.', ru: 'ответов.' },
  'About the studio': { ka: 'სტუდიის შესახებ', ru: 'О студии' }, 'Small by choice.': { ka: 'პატარა — შეგნებულად.', ru: 'Небольшая — осознанно.' }, 'Invested by nature.': { ka: 'სრულად ჩართული.', ru: 'Полная вовлечённость.' }, 'Salyior is an independent web studio founded by David, helping businesses in Batumi, Tbilisi and across Georgia put their best foot forward online.': { ka: 'Salyior დავითის მიერ დაარსებული დამოუკიდებელი ვებსტუდიაა, რომელიც ბათუმის, თბილისის და მთელი საქართველოს ბიზნესებს ონლაინ უკეთ წარმოჩენაში ეხმარება.', ru: 'Salyior — независимая веб-студия Давида, которая помогает бизнесу в Батуми, Тбилиси и по всей Грузии достойно выглядеть онлайн.' }, 'A note from David': { ka: 'დავითისგან', ru: 'Слово Давида' }, '“Your website should reflect the care you put into your business.”': { ka: '„თქვენი ვებსაიტი უნდა ასახავდეს იმ ზრუნვას, რომელსაც ბიზნესში დებთ.“', ru: '«Ваш сайт должен отражать ту заботу, которую вы вкладываете в бизнес».' }, 'A real person.': { ka: 'რეალური ადამიანი.', ru: 'Реальный человек.' }, 'One clear responsibility.': { ka: 'ერთი მკაფიო პასუხისმგებლობა.', ru: 'Одна понятная ответственность.' }, 'You work directly with the person designing and building your website. Clear conversations, thoughtful decisions and attention to the details that matter.': { ka: 'თქვენ პირდაპირ მუშაობთ ადამიანთან, რომელიც თქვენს ვებსაიტს ქმნის. მკაფიო საუბარი, გააზრებული გადაწყვეტილებები და ყურადღება მნიშვნელოვან დეტალებზე.', ru: 'Вы напрямую работаете с человеком, который проектирует и создаёт ваш сайт. Понятное общение, продуманные решения и внимание к важным деталям.' }, 'Designed around your business': { ka: 'თქვენს ბიზნესზე მორგებული', ru: 'Создано вокруг вашего бизнеса' }, 'Quality beyond the first impression': { ka: 'ხარისხი პირველი შთაბეჭდილების მიღმა', ru: 'Качество глубже первого впечатления' }, 'A clear handover and next steps': { ka: 'მკაფიო ჩაბარება და შემდეგი ნაბიჯები', ru: 'Понятная передача и следующие шаги' },
  'Your details, treated with care.': { ka: 'თქვენი მონაცემები დაცულია.', ru: 'Бережно к вашим данным.' }, 'A short explanation of how enquiries are handled.': { ka: 'მოკლე განმარტება, თუ როგორ მუშავდება მოთხოვნები.', ru: 'Кратко о том, как обрабатываются обращения.' }, 'When you contact Salyior': { ka: 'როდესაც Salyior-ს უკავშირდებით', ru: 'Когда вы связываетесь с Salyior' }, 'Your name, email and project details are used to review and respond to your enquiry. Please include only the information needed to discuss your website.': { ka: 'თქვენი სახელი, ელფოსტა და პროექტის დეტალები გამოიყენება მოთხოვნის განსახილველად და პასუხისთვის. გთხოვთ, მიუთითოთ მხოლოდ საჭირო ინფორმაცია.', ru: 'Ваше имя, почта и сведения о проекте используются для рассмотрения запроса и ответа. Указывайте только необходимую информацию.' }, 'Sending an enquiry': { ka: 'მოთხოვნის გაგზავნა', ru: 'Отправка запроса' }, 'On the local preview, the form prepares a draft in your email app. You choose whether to send it. On the published site, enquiries may be delivered through our email provider. If delivery is unavailable, a direct email option is shown.': { ka: 'ლოკალურ ვერსიაში ფორმა ამზადებს ელფოსტის მონახაზს და თქვენ წყვეტთ მის გაგზავნას. გამოქვეყნებულ ვერსიაში მოთხოვნა შეიძლება გაიგზავნოს ელფოსტის სერვისით. შეფერხების შემთხვევაში გამოჩნდება პირდაპირი ელფოსტის ბმული.', ru: 'В локальной версии форма создаёт черновик письма, и вы решаете, отправлять ли его. На опубликованном сайте запрос может отправляться через почтовый сервис. Если это недоступно, появится прямая ссылка на почту.' }, 'Cookies and analytics': { ka: 'ქუქიები და ანალიტიკა', ru: 'Файлы cookie и аналитика' }, 'This website does not set marketing cookies or include an analytics tracker.': { ka: 'ეს ვებსაიტი არ იყენებს მარკეტინგულ ქუქიებს ან ანალიტიკის ტრეკერს.', ru: 'Этот сайт не использует маркетинговые cookie или трекер аналитики.' }, 'Questions or removal requests': { ka: 'კითხვები ან წაშლის მოთხოვნა', ru: 'Вопросы или удаление данных' }, 'Email': { ka: 'მოგვწერეთ', ru: 'Напишите на' }, 'to ask about your enquiry details or request their removal.': { ka: 'თქვენი მოთხოვნის მონაცემების შესახებ კითხვის ან მათი წაშლის მოთხოვნისთვის.', ru: 'чтобы уточнить данные обращения или запросить их удаление.' },
  'Page not found': { ka: 'გვერდი ვერ მოიძებნა', ru: 'Страница не найдена' }, 'Let’s get you back.': { ka: 'დაგაბრუნებთ უკან.', ru: 'Вернём вас назад.' }, 'This page isn’t available.': { ka: 'ეს გვერდი მიუწვდომელია.', ru: 'Эта страница недоступна.' }, 'Back to the homepage': { ka: 'მთავარ გვერდზე დაბრუნება', ru: 'На главную' },
  'Is SEO included?': { ka: 'შედის თუ არა SEO?', ru: 'SEO включено?' }, 'Every website includes technical and on-page SEO foundations. Ongoing content and SEO work can be scoped separately.': { ka: 'ყველა ვებსაიტი მოიცავს ტექნიკური და შიდა SEO-ს საფუძვლებს. მუდმივი კონტენტი და SEO ცალკე შეიძლება დაიგეგმოს.', ru: 'Каждый сайт включает основы технического и внутреннего SEO. Постоянную работу с контентом и SEO можно заказать отдельно.' }, 'How much will my website cost?': { ka: 'რა ეღირება ჩემი ვებსაიტი?', ru: 'Сколько будет стоить мой сайт?' }, 'It depends on the pages, content and features. We agree the scope and price before work starts.': { ka: 'ფასი დამოკიდებულია გვერდებზე, კონტენტსა და ფუნქციებზე. მოცულობასა და ფასს მუშაობის დაწყებამდე ვათანხმებთ.', ru: 'Цена зависит от страниц, контента и функций. Объём и стоимость согласуются до начала работы.' }, 'Can we start with a call?': { ka: 'შეგვიძლია ზარით დავიწყოთ?', ru: 'Можно начать со звонка?' }, 'Of course. Send a call request with a convenient time, or call David directly. We’ll confirm a time together.': { ka: 'რა თქმა უნდა. გამოგვიგზავნეთ ზარის მოთხოვნა სასურველი დროით ან პირდაპირ დაურეკეთ დავითს. დროს ერთად დავადასტურებთ.', ru: 'Конечно. Отправьте запрос с удобным временем или позвоните Давиду напрямую. Мы подтвердим время.' }, 'What happens after launch?': { ka: 'რა ხდება გაშვების შემდეგ?', ru: 'Что происходит после запуска?' }, 'We agree the handover and any ongoing support as part of your project.': { ka: 'პროექტის ფარგლებში წინასწარ ვათანხმებთ ჩაბარებასა და შემდგომ მხარდაჭერას.', ru: 'Передача сайта и дальнейшая поддержка согласуются в рамках проекта.' },
  'Web design, websites and web application development for businesses in Batumi, Tbilisi and across Georgia. Fast, multilingual and built for enquiries.': { ka: 'ვებდიზაინი, ვებსაიტები და ვებაპლიკაციები ბათუმის, თბილისის და მთელი საქართველოს ბიზნესებისთვის. სწრაფი, მრავალენოვანი და მომართვებზე ორიენტირებული.', ru: 'Веб-дизайн, сайты и веб-приложения для бизнеса в Батуми, Тбилиси и по всей Грузии. Быстро, на трёх языках и с фокусом на заявки.' },
  'Web design & web app development in Batumi': { ka: 'ვებდიზაინი და ვებაპლიკაციების შექმნა ბათუმში', ru: 'Веб-дизайн и разработка веб-приложений в Батуми' }, 'Web design portfolio': { ka: 'ვებდიზაინის პორტფოლიო', ru: 'Портфолио веб-дизайна' }, 'Web design, development & SEO services': { ka: 'ვებდიზაინი, დეველოპმენტი და SEO', ru: 'Веб-дизайн, разработка и SEO' }, 'Website design process': { ka: 'ვებსაიტის შექმნის პროცესი', ru: 'Процесс создания сайта' }, 'Website pricing': { ka: 'ვებსაიტის ფასები', ru: 'Цены на сайты' }, 'Web studio in Batumi': { ka: 'ვებსტუდია ბათუმში', ru: 'Веб-студия в Батуми' }, 'Discuss your website project': { ka: 'განიხილეთ თქვენი ვებსაიტის პროექტი', ru: 'Обсудить ваш сайт' },
  'Selected websites and web applications created by Salyior for businesses in Georgia and beyond.': { ka: 'Salyior-ის მიერ შექმნილი ვებსაიტები და ვებაპლიკაციები საქართველოსა და სხვა ქვეყნების ბიზნესებისთვის.', ru: 'Избранные сайты и веб-приложения Salyior для бизнеса в Грузии и за её пределами.' },
  'Web design, development, local SEO, performance and web application services in Batumi and Tbilisi, Georgia.': { ka: 'ვებდიზაინი, დეველოპმენტი, ლოკალური SEO, სისწრაფე და ვებაპლიკაციები ბათუმსა და თბილისში.', ru: 'Веб-дизайн, разработка, локальное SEO, скорость и веб-приложения в Батуми и Тбилиси.' },
  'A clear website design and development process from discovery to launch.': { ka: 'ვებსაიტის დიზაინისა და დეველოპმენტის მკაფიო პროცესი კვლევიდან გაშვებამდე.', ru: 'Понятный процесс дизайна и разработки сайта — от исследования до запуска.' },
  'Website design and development packages for businesses in Batumi, Tbilisi and across Georgia.': { ka: 'ვებსაიტის დიზაინისა და დეველოპმენტის პაკეტები ბათუმის, თბილისის და მთელი საქართველოს ბიზნესებისთვის.', ru: 'Пакеты дизайна и разработки сайтов для бизнеса в Батуми, Тбилиси и по всей Грузии.' },
  'Meet Salyior, an independent web design and development studio based in Batumi, Georgia.': { ka: 'გაიცანით Salyior — დამოუკიდებელი ვებდიზაინისა და დეველოპმენტის სტუდია ბათუმში.', ru: 'Познакомьтесь с Salyior — независимой студией веб-дизайна и разработки из Батуми.' },
  'Discuss a website or web application project with Salyior in Batumi, Georgia.': { ka: 'განიხილეთ ვებსაიტის ან ვებაპლიკაციის პროექტი Salyior-თან ბათუმში.', ru: 'Обсудите сайт или веб-приложение с Salyior в Батуми.' },
  'Websites and web applications designed and developed by Salyior in Batumi, Georgia.': { ka: 'Salyior-ის მიერ ბათუმში შექმნილი ვებსაიტები და ვებაპლიკაციები.', ru: 'Сайты и веб-приложения, созданные Salyior в Батуми.' },
  'Please add your name and a short message.': { ka: 'გთხოვთ, მიუთითოთ სახელი და მოკლე შეტყობინება.', ru: 'Укажите имя и короткое сообщение.' },
  'Your email draft is ready. If your email app didn’t open, use this link.': { ka: 'ელფოსტის მონახაზი მზადაა. თუ აპი არ გაიხსნა, გამოიყენეთ ეს ბმული.', ru: 'Черновик письма готов. Если почтовое приложение не открылось, используйте эту ссылку.' }, 'Your message couldn’t be delivered. Please use the email link below.': { ka: 'შეტყობინება ვერ გაიგზავნა. გამოიყენეთ ქვემოთ მოცემული ელფოსტის ბმული.', ru: 'Сообщение не отправилось. Используйте ссылку на почту ниже.' }, 'Please email us directly.': { ka: 'გთხოვთ, მოგვწეროთ პირდაპირ ელფოსტაზე.', ru: 'Напишите нам напрямую по электронной почте.' },
  'Design that earns trust.': { ka: 'დიზაინი, რომელიც ნდობას ქმნის.', ru: 'Дизайн, который вызывает доверие.' }, 'A distinctive website that makes your business easy to understand and your next step easy to find.': { ka: 'გამორჩეული ვებსაიტი, რომელიც თქვენს ბიზნესს გასაგებს ხდის და შემდეგ ნაბიჯს მარტივად აჩვენებს.', ru: 'Выразительный сайт, который понятно представляет бизнес и показывает следующий шаг.' }, 'Custom visual direction': { ka: 'ინდივიდუალური ვიზუალური მიმართულება', ru: 'Индивидуальное визуальное направление' }, 'Responsive development': { ka: 'ადაპტიური დეველოპმენტი', ru: 'Адаптивная разработка' }, 'Clear content structure': { ka: 'კონტენტის მკაფიო სტრუქტურა', ru: 'Понятная структура контента' },
  'A stronger start in search.': { ka: 'ძლიერი დასაწყისი ძიებაში.', ru: 'Сильный старт в поиске.' }, 'Fast, search-friendly pages that help people and search engines understand what you offer.': { ka: 'სწრაფი, საძიებო სისტემებზე მორგებული გვერდები, რომლებიც ადამიანებსა და Google-ს თქვენს შეთავაზებას უკეთ აცნობს.', ru: 'Быстрые страницы, которые помогают людям и поисковым системам понять ваше предложение.' }, 'Page titles & descriptions': { ka: 'გვერდების სათაურები და აღწერები', ru: 'Заголовки и описания страниц' }, 'Performance optimisation': { ka: 'სისწრაფის ოპტიმიზაცია', ru: 'Оптимизация скорости' }, 'Indexing & sitemap foundations': { ka: 'ინდექსაცია და საიტის რუკა', ru: 'Индексация и карта сайта' },
  'Lead generation': { ka: 'ლიდების გენერაცია', ru: 'Получение заявок' }, 'From interest to enquiry.': { ka: 'ინტერესიდან მომართვამდე.', ru: 'От интереса к заявке.' }, 'Purposeful contact actions and straightforward forms that help visitors reach you.': { ka: 'მკაფიო საკონტაქტო მოქმედებები და მარტივი ფორმები, რომლებიც მომხმარებელს თქვენთან დაკავშირებაში ეხმარება.', ru: 'Понятные контакты и простые формы, которые помогают посетителю связаться с вами.' }, 'Clear customer journeys': { ka: 'მომხმარებლის მკაფიო გზა', ru: 'Понятный путь клиента' }, 'Enquiry paths & forms': { ka: 'საკონტაქტო გზები და ფორმები', ru: 'Пути обращения и формы' }, 'Analytics setup when agreed': { ka: 'ანალიტიკის დაყენება შეთანხმებით', ru: 'Настройка аналитики по согласованию' },
  'Useful beyond the homepage.': { ka: 'სასარგებლო მთავარ გვერდს მიღმაც.', ru: 'Полезно не только на главной.' }, 'The right tools for your customers, from menus and collections to booking integrations.': { ka: 'სწორი ხელსაწყოები თქვენი მომხმარებლებისთვის — მენიუებიდან და კოლექციებიდან ჯავშნის ინტეგრაციამდე.', ru: 'Нужные клиентам инструменты — от меню и каталогов до интеграции бронирования.' }, 'Menus & product collections': { ka: 'მენიუები და პროდუქტების კოლექციები', ru: 'Меню и каталоги товаров' }, 'Booking integrations': { ka: 'ჯავშნის ინტეგრაციები', ru: 'Интеграции бронирования' }, 'Content editing when needed': { ka: 'კონტენტის რედაქტირება საჭიროებისას', ru: 'Редактирование контента при необходимости' },
  'Your workflow. Made simpler.': { ka: 'თქვენი სამუშაო პროცესი — გამარტივებული.', ru: 'Ваш рабочий процесс — проще.' }, 'Custom browser-based tools for the way your business works. A useful experience for your customers or your team.': { ka: 'თქვენი ბიზნესის მუშაობაზე მორგებული ვებხელსაწყოები მომხმარებლებისა და გუნდისთვის.', ru: 'Веб-инструменты под процессы вашего бизнеса — для клиентов или команды.' }, 'Customer portals': { ka: 'მომხმარებლის პორტალები', ru: 'Клиентские порталы' }, 'Dashboards & internal tools': { ka: 'დეშბორდები და შიდა ხელსაწყოები', ru: 'Панели и внутренние инструменты' }, 'Tailored workflows': { ka: 'მორგებული სამუშაო პროცესები', ru: 'Индивидуальные процессы' },
  'A conversation.': { ka: 'საუბარი.', ru: 'Разговор.' }, 'We learn your business, audience and goals.': { ka: 'ვიცნობთ თქვენს ბიზნესს, აუდიტორიასა და მიზნებს.', ru: 'Изучаем ваш бизнес, аудиторию и цели.' }, 'Together, we agree the pages, features, content and price before the build begins.': { ka: 'შექმნის დაწყებამდე ერთად ვათანხმებთ გვერდებს, ფუნქციებს, კონტენტსა და ფასს.', ru: 'До начала работы вместе согласуем страницы, функции, контент и цену.' }, 'A clear scope & quote': { ka: 'მკაფიო მოცულობა და შეთავაზება', ru: 'Понятный объём и смета' },
  'A clear direction.': { ka: 'მკაფიო მიმართულება.', ru: 'Понятное направление.' }, 'We shape the story and visual direction.': { ka: 'ვაყალიბებთ ისტორიასა და ვიზუალურ მიმართულებას.', ru: 'Формируем историю и визуальное направление.' }, 'You review the layout and design, with room to give feedback before we move forward.': { ka: 'თქვენ ამოწმებთ სტრუქტურასა და დიზაინს და გვაძლევთ უკუკავშირს შემდეგ ეტაპამდე.', ru: 'Вы проверяете структуру и дизайн и даёте обратную связь до следующего этапа.' }, 'A design to review': { ka: 'დიზაინი შესაფასებლად', ru: 'Дизайн для согласования' },
  'Built with care.': { ka: 'შექმნილი ზრუნვით.', ru: 'Создано с вниманием.' }, 'We develop, refine and check the details.': { ka: 'ვავითარებთ, ვხვეწავთ და ვამოწმებთ დეტალებს.', ru: 'Разрабатываем, дорабатываем и проверяем детали.' }, 'Responsive layouts, performance, SEO foundations and contact actions come together.': { ka: 'ერთიანდება ადაპტიური დიზაინი, სისწრაფე, SEO და საკონტაქტო მოქმედებები.', ru: 'Объединяем адаптивный дизайн, скорость, основы SEO и контактные действия.' }, 'A working website preview': { ka: 'ვებსაიტის სამუშაო ვერსია', ru: 'Рабочая версия сайта' },
  'Ready to launch.': { ka: 'მზადაა გასაშვებად.', ru: 'Готово к запуску.' }, 'We review the finished website together.': { ka: 'ერთად ვამოწმებთ დასრულებულ ვებსაიტს.', ru: 'Вместе проверяем готовый сайт.' }, 'Final checks, launch and a handover. Any ongoing support is agreed around your needs.': { ka: 'საბოლოო შემოწმება, გაშვება და ჩაბარება. შემდგომ მხარდაჭერას თქვენს საჭიროებებზე ვათანხმებთ.', ru: 'Финальная проверка, запуск и передача. Дальнейшую поддержку согласуем под ваши потребности.' }, 'Launch & handover': { ka: 'გაშვება და ჩაბარება', ru: 'Запуск и передача' },
  'Essential': { ka: 'საბაზისო', ru: 'Базовый' }, 'A focused introduction to your business.': { ka: 'თქვენი ბიზნესის მიზანმიმართული წარდგენა.', ru: 'Сфокусированное представление бизнеса.' }, 'One-page website': { ka: 'ერთგვერდიანი ვებსაიტი', ru: 'Одностраничный сайт' }, 'Custom one-page design': { ka: 'ინდივიდუალური ერთგვერდიანი დიზაინი', ru: 'Индивидуальный дизайн одной страницы' }, 'SEO & performance foundations': { ka: 'SEO-სა და სისწრაფის საფუძვლები', ru: 'Основы SEO и скорости' }, 'Mobile-ready contact form': { ka: 'მობილურზე მორგებული ფორმა', ru: 'Удобная мобильная форма' }, 'A new business or a single service.': { ka: 'ახალი ბიზნესი ან ერთი სერვისი.', ru: 'Новый бизнес или одна услуга.' },
  'Business': { ka: 'ბიზნესი', ru: 'Бизнес' }, 'Room for your services, story and proof.': { ka: 'სივრცე თქვენი სერვისების, ისტორიისა და შედეგებისთვის.', ru: 'Место для услуг, истории и доказательств.' }, 'Multi-page website': { ka: 'მრავალგვერდიანი ვებსაიტი', ru: 'Многостраничный сайт' }, 'Custom multi-page design': { ka: 'ინდივიდუალური მრავალგვერდიანი დიზაინი', ru: 'Индивидуальный многостраничный дизайн' }, 'Enquiry & measurement setup': { ka: 'მომართვებისა და გაზომვის დაყენება', ru: 'Настройка заявок и измерения' }, 'An established business ready to grow.': { ka: 'ჩამოყალიბებული ბიზნესი, რომელიც ზრდისთვის მზადაა.', ru: 'Развивающийся состоявшийся бизнес.' },
  'Custom': { ka: 'ინდივიდუალური', ru: 'Индивидуальный' }, 'A website shaped around how you work.': { ka: 'თქვენს მუშაობაზე მორგებული ვებსაიტი.', ru: 'Сайт под ваши рабочие процессы.' }, 'Tailored experience': { ka: 'მორგებული გამოცდილება', ru: 'Индивидуальный проект' }, 'Custom design & features': { ka: 'ინდივიდუალური დიზაინი და ფუნქციები', ru: 'Индивидуальный дизайн и функции' }, 'Bookings or tailored workflows': { ka: 'ჯავშნები ან მორგებული პროცესები', ru: 'Бронирование или особые процессы' }, 'SEO & measurement setup': { ka: 'SEO-სა და გაზომვის დაყენება', ru: 'Настройка SEO и измерения' }, 'A business with specific functionality.': { ka: 'ბიზნესი სპეციფიკური ფუნქციონალით.', ru: 'Бизнесу с особыми функциями.' },
  'Education': { ka: 'განათლება', ru: 'Образование' }, 'Hospitality': { ka: 'მასპინძლობა', ru: 'Гостеприимство' }, 'Travel': { ka: 'მოგზაურობა', ru: 'Путешествия' }, 'Commerce': { ka: 'კომერცია', ru: 'Коммерция' }, 'Client project': { ka: 'კლიენტის პროექტი', ru: 'Клиентский проект' }, 'Website demo': { ka: 'სადემონსტრაციო ვებსაიტი', ru: 'Демо-сайт' }, 'Portfolio project': { ka: 'პორტფოლიოს პროექტი', ru: 'Проект портфолио' },
  'A considered digital home for exceptional properties.': { ka: 'გააზრებული ციფრული სივრცე გამორჩეული უძრავი ქონებისთვის.', ru: 'Продуманное цифровое пространство для особенной недвижимости.' }, 'An image-led property experience with collection browsing and a clear path to private enquiries.': { ka: 'ვიზუალებზე დაფუძნებული უძრავი ქონების გამოცდილება კოლექციის დათვალიერებითა და პირადი მოთხოვნის მკაფიო გზით.', ru: 'Визуальная подача недвижимости с просмотром коллекции и понятным путём к частному запросу.' }, 'Property collection': { ka: 'უძრავი ქონების კოლექცია', ru: 'Коллекция объектов' }, 'Editorial presentation': { ka: 'სარედაქციო პრეზენტაცია', ru: 'Редакционная подача' }, 'Enquiry journey': { ka: 'მომართვის გზა', ru: 'Путь к обращению' },
  'A personal introduction to learning Georgian.': { ka: 'ქართული ენის სწავლების პირადი და თბილი წარდგენა.', ru: 'Личное знакомство с изучением грузинского языка.' }, 'A clear, welcoming website that introduces the tutor, explains lesson formats and makes the first conversation easier.': { ka: 'მკაფიო და მეგობრული ვებსაიტი, რომელიც მასწავლებელს წარადგენს, გაკვეთილების ფორმატებს ხსნის და პირველ საუბარს ამარტივებს.', ru: 'Понятный и дружелюбный сайт, который знакомит с преподавателем, объясняет форматы занятий и упрощает первый контакт.' }, 'Tutor introduction': { ka: 'მასწავლებლის წარდგენა', ru: 'Знакомство с преподавателем' }, 'Lesson formats': { ka: 'გაკვეთილების ფორმატები', ru: 'Форматы занятий' }, 'Contact actions': { ka: 'საკონტაქტო მოქმედებები', ru: 'Контактные действия' },
  'A restaurant’s atmosphere, brought to the screen.': { ka: 'რესტორნის ატმოსფერო ეკრანზე.', ru: 'Атмосфера ресторана на экране.' }, 'An atmospheric restaurant website with menu browsing, a gallery and reservation prompts.': { ka: 'ატმოსფერული რესტორნის ვებსაიტი მენიუთი, გალერეითა და დაჯავშნის მოწოდებებით.', ru: 'Атмосферный сайт ресторана с меню, галереей и предложением забронировать стол.' }, 'Menu browsing': { ka: 'მენიუს დათვალიერება', ru: 'Просмотр меню' }, 'Restaurant gallery': { ka: 'რესტორნის გალერეა', ru: 'Галерея ресторана' }, 'Reservation prompts': { ka: 'დაჯავშნის მოწოდებები', ru: 'Призывы к бронированию' },
  'A calmer start in an unfamiliar city.': { ka: 'უფრო მშვიდი დასაწყისი უცნობ ქალაქში.', ru: 'Спокойное начало в незнакомом городе.' }, 'A city-arrival guide that brings transport, stays, food and local essentials into one browsing experience.': { ka: 'ქალაქში ჩასვლის გზამკვლევი, რომელიც ტრანსპორტს, საცხოვრებელს, კვებასა და ადგილობრივ საჭიროებებს ერთ სივრცეში აერთიანებს.', ru: 'Гид по прибытию в город, объединяющий транспорт, жильё, еду и местные советы.' }, 'City guides': { ka: 'ქალაქის გზამკვლევები', ru: 'Городские гиды' }, 'Travel information': { ka: 'სამოგზაურო ინფორმაცია', ru: 'Информация для поездки' }, 'Content discovery': { ka: 'კონტენტის აღმოჩენა', ru: 'Поиск контента' },
  'A clear invitation to a memorable evening.': { ka: 'მკაფიო მოწვევა დასამახსოვრებელ საღამოზე.', ru: 'Ясное приглашение на запоминающийся вечер.' }, 'Restaurant presentation that balances atmosphere with useful menus, opening hours and location information.': { ka: 'რესტორნის პრეზენტაცია, რომელიც ატმოსფეროს მენიუსთან, სამუშაო საათებთან და მდებარეობასთან აბალანსებს.', ru: 'Презентация ресторана, сочетающая атмосферу с меню, часами работы и адресом.' }, 'Restaurant identity': { ka: 'რესტორნის იდენტობა', ru: 'Образ ресторана' }, 'Menu presentation': { ka: 'მენიუს პრეზენტაცია', ru: 'Подача меню' }, 'Visit information': { ka: 'ვიზიტის ინფორმაცია', ru: 'Информация для визита' },
  'An elegant setting for European cuisine.': { ka: 'ელეგანტური სივრცე ევროპული სამზარეულოსთვის.', ru: 'Элегантное пространство для европейской кухни.' }, 'A restaurant experience centred on menu presentation, atmospheric visuals and reservation prompts.': { ka: 'რესტორნის გამოცდილება მენიუს პრეზენტაციით, ატმოსფერული ვიზუალებითა და დაჯავშნის მოწოდებებით.', ru: 'Сайт ресторана с акцентом на меню, атмосферные визуалы и бронирование.' }, 'Restaurant visuals': { ka: 'რესტორნის ვიზუალები', ru: 'Визуалы ресторана' }, 'Reservation journey': { ka: 'დაჯავშნის გზა', ru: 'Путь бронирования' },
  'A storefront with a personality of its own.': { ka: 'ონლაინ მაღაზია საკუთარი ხასიათით.', ru: 'Витрина с собственным характером.' }, 'A playful custom portrait website with distinctive visual direction and clear commission prompts.': { ka: 'თამაშიანი პორტრეტების ვებსაიტი გამორჩეული ვიზუალური მიმართულებითა და შეკვეთის მკაფიო გზით.', ru: 'Игривый сайт портретов с выразительным стилем и понятным заказом.' }, 'Portrait commissions': { ka: 'პორტრეტების შეკვეთები', ru: 'Заказы портретов' }, 'Visual identity': { ka: 'ვიზუალური იდენტობა', ru: 'Визуальная айдентика' }, 'Ordering prompts': { ka: 'შეკვეთის მოწოდებები', ru: 'Призывы к заказу' },
  'Fresh presentation. Straightforward ordering.': { ka: 'ახალი პრეზენტაცია. მარტივი შეკვეთა.', ru: 'Свежая подача. Простой заказ.' }, 'A mobile-friendly food ordering interface with clear products, ingredients and browsing.': { ka: 'მობილურზე მორგებული საკვების შეკვეთის ინტერფეისი მკაფიო პროდუქტებითა და ინგრედიენტებით.', ru: 'Удобный мобильный интерфейс заказа еды с понятными товарами и ингредиентами.' }, 'Product catalogue': { ka: 'პროდუქტების კატალოგი', ru: 'Каталог товаров' }, 'Ingredient information': { ka: 'ინგრედიენტების ინფორმაცია', ru: 'Информация об ингредиентах' }, 'Mobile ordering': { ka: 'მობილური შეკვეთა', ru: 'Мобильный заказ' },
  'An inviting first taste of a neighbourhood café.': { ka: 'სამეზობლო კაფეს მიმზიდველი პირველი შთაბეჭდილება.', ru: 'Привлекательное первое знакомство с уютным кафе.' }, 'A café website built around coffee, menu highlights, photography and practical visit details.': { ka: 'კაფეს ვებსაიტი ყავის, მენიუს გამორჩეული პოზიციების, ფოტოების და ვიზიტის დეტალების გარშემო.', ru: 'Сайт кафе о кофе, главных позициях меню, фотографиях и полезной информации для визита.' }, 'Menu highlights': { ka: 'მენიუს გამორჩეული პოზიციები', ru: 'Главное в меню' }, 'Photo gallery': { ka: 'ფოტოგალერეა', ru: 'Фотогалерея' }, 'Opening information': { ka: 'სამუშაო საათები', ru: 'Часы работы' },
  'Web design in Batumi': { ka: 'ვებდიზაინი ბათუმში', ru: 'Веб-дизайн в Батуми' }, 'Web design in Tbilisi': { ka: 'ვებდიზაინი თბილისში', ru: 'Веб-дизайн в Тбилиси' }, 'Websites for Batumi businesses.': { ka: 'ვებსაიტები ბათუმის ბიზნესებისთვის.', ru: 'Сайты для бизнеса в Батуми.' }, 'Websites for Tbilisi businesses.': { ka: 'ვებსაიტები თბილისის ბიზნესებისთვის.', ru: 'Сайты для бизнеса в Тбилиси.' }, 'Built to be found.': { ka: 'შექმნილი ხილვადობისთვის.', ru: 'Создано, чтобы вас находили.' },
  'Local web design, development and multilingual SEO for businesses in Batumi, Georgia.': { ka: 'ლოკალური ვებდიზაინი, დეველოპმენტი და მრავალენოვანი SEO ბათუმის ბიზნესებისთვის.', ru: 'Локальный веб-дизайн, разработка и многоязычное SEO для бизнеса в Батуми.' }, 'Web design, development and multilingual SEO for businesses in Tbilisi, Georgia.': { ka: 'ვებდიზაინი, დეველოპმენტი და მრავალენოვანი SEO თბილისის ბიზნესებისთვის.', ru: 'Веб-дизайн, разработка и многоязычное SEO для бизнеса в Тбилиси.' },
  'Local web design, development and SEO for hotels, restaurants, property businesses and growing teams in Batumi.': { ka: 'ლოკალური ვებდიზაინი, დეველოპმენტი და SEO ბათუმის სასტუმროებისთვის, რესტორნებისთვის, უძრავი ქონებისა და მზარდი ბიზნესებისთვის.', ru: 'Локальный веб-дизайн, разработка и SEO для отелей, ресторанов, недвижимости и растущего бизнеса в Батуми.' }, 'Web design, development and multilingual SEO for ambitious businesses and growing teams in Tbilisi.': { ka: 'ვებდიზაინი, დეველოპმენტი და მრავალენოვანი SEO ამბიციური ბიზნესებისა და მზარდი გუნდებისთვის თბილისში.', ru: 'Веб-дизайн, разработка и многоязычное SEO для амбициозного бизнеса и растущих команд в Тбилиси.' },
  'LOCAL DISCOVERY': { ka: 'ლოკალური ხილვადობა', ru: 'ЛОКАЛЬНАЯ ВИДИМОСТЬ' }, 'LEADS & SALES': { ka: 'ლიდები და გაყიდვები', ru: 'ЗАЯВКИ И ПРОДАЖИ' }, 'Be clear about what you offer—and where.': { ka: 'მკაფიოდ აჩვენეთ რას სთავაზობთ და სად.', ru: 'Покажите, что и где вы предлагаете.' }, 'Language-specific pages, useful service content and technical signals help Google connect your business with relevant searches in Georgia.': { ka: 'ენების მიხედვით ცალკე გვერდები, სასარგებლო სერვისის კონტენტი და ტექნიკური სიგნალები Google-ს ეხმარება თქვენი ბიზნესი საქართველოს შესაბამის ძიებებს დაუკავშიროს.', ru: 'Отдельные языковые страницы, полезный контент об услугах и технические сигналы помогают Google связывать ваш бизнес с релевантными запросами в Грузии.' }, 'English, Georgian and Russian pages': { ka: 'ინგლისური, ქართული და რუსული გვერდები', ru: 'Страницы на английском, грузинском и русском' }, 'Local service and location signals': { ka: 'ლოკალური სერვისისა და მდებარეობის სიგნალები', ru: 'Сигналы услуг и местоположения' }, 'Search-friendly structure and metadata': { ka: 'ძიებისთვის მორგებული სტრუქტურა და მეტამონაცემები', ru: 'Структура и метаданные для поиска' }, 'Turn local visits into conversations.': { ka: 'ადგილობრივი ვიზიტები გადააქციეთ საუბრებად.', ru: 'Превращайте местные посещения в обращения.' }, 'Fast mobile pages, strong proof and clear contact actions make it easier for a potential customer to choose your business.': { ka: 'სწრაფი მობილური გვერდები, ძლიერი მტკიცებულებები და მკაფიო საკონტაქტო მოქმედებები პოტენციურ მომხმარებელს არჩევანს უმარტივებს.', ru: 'Быстрые мобильные страницы, убедительные примеры и понятные контакты упрощают выбор потенциальному клиенту.' }, 'Fast mobile experience': { ka: 'სწრაფი მობილური გამოცდილება', ru: 'Быстрый мобильный опыт' }, 'Clear enquiry paths': { ka: 'მომართვის მკაფიო გზები', ru: 'Понятные пути обращения' }, 'Measurement-ready conversion points': { ka: 'გასაზომად მზად კონვერსიის წერტილები', ru: 'Готовые к измерению точки конверсии' },
  'Get found.': { ka: 'გიპოვონ.', ru: 'Пусть вас находят.' }, 'Get chosen.': { ka: 'აგირჩიონ.', ru: 'Пусть выбирают вас.' },
  'Fast, search-ready websites that help new customers discover your business, trust what they see and get in touch.': { ka: 'სწრაფი, ძიებისთვის მომზადებული ვებსაიტები, რომლებიც ახალ მომხმარებლებს ეხმარება აღმოაჩინონ თქვენი ბიზნესი, ენდონ ნანახს და დაგიკავშირდნენ.', ru: 'Быстрые сайты, готовые к поисковому продвижению: новые клиенты находят ваш бизнес, доверяют увиденному и связываются с вами.' },
  'Build my website': { ka: 'შექმენით ჩემი ვებსაიტი', ru: 'Создать мой сайт' }, 'Clear scope. Direct contact. Built around your goals.': { ka: 'მკაფიო მოცულობა. პირდაპირი კონტაქტი. თქვენს მიზნებზე მორგებული.', ru: 'Понятный объём. Прямой контакт. Всё вокруг ваших целей.' },
  'WEBSITES BUILT TO WIN ATTENTION': { ka: 'ვებსაიტები, რომლებიც ყურადღებას იქცევს', ru: 'САЙТЫ, КОТОРЫЕ ПРИВЛЕКАЮТ ВНИМАНИЕ' }, 'Your website should earn its place.': { ka: 'თქვენი ვებსაიტი ბიზნესს უნდა ემსახურებოდეს.', ru: 'Ваш сайт должен работать на бизнес.' }, 'Get found': { ka: 'გიპოვონ', ru: 'Найдут' }, 'Build trust': { ka: 'ნდობის შექმნა', ru: 'Доверятся' }, 'Win enquiries': { ka: 'მეტი მომართვა', ru: 'Обратятся' },
  'Websites people remember': { ka: 'ვებსაიტები, რომლებიც ახსოვთ', ru: 'Сайты, которые запоминают' }, 'Make your business': { ka: 'წარმოაჩინეთ თქვენი ბიზნესი', ru: 'Покажите свой бизнес' }, 'look like the right choice.': { ka: 'როგორც სწორი არჩევანი.', ru: 'как правильный выбор.' },
  'From search to enquiry': { ka: 'ძიებიდან მომართვამდე', ru: 'От поиска до обращения' }, 'First they find you.': { ka: 'ჯერ გპოულობენ.', ru: 'Сначала вас находят.' }, 'Then they choose you.': { ka: 'შემდეგ გირჩევენ.', ru: 'Затем выбирают вас.' }, 'We combine search visibility, clear messages and purposeful design so more of the right people contact your business.': { ka: 'ვაერთიანებთ საძიებო ხილვადობას, მკაფიო ტექსტებსა და მიზანმიმართულ დიზაინს, რათა თქვენს ბიზნესს მეტი სწორი მომხმარებელი დაუკავშირდეს.', ru: 'Мы объединяем видимость в поиске, понятные тексты и продуманный дизайн, чтобы больше нужных клиентов обращались именно к вам.' }, 'See how we help': { ka: 'ნახეთ, როგორ გეხმარებით', ru: 'Как мы помогаем' },
  'Easy to start': { ka: 'მარტივი დასაწყისი', ru: 'Легко начать' }, 'Your business. Your goals.': { ka: 'თქვენი ბიზნესი. თქვენი მიზნები.', ru: 'Ваш бизнес. Ваши цели.' }, 'A website built to support both.': { ka: 'ვებსაიტი, რომელიც ორივეს ემსახურება.', ru: 'Сайт, который работает на оба.' }, 'We agree what your website needs to achieve, create the right direction and launch it with a clear path for customers to contact you.': { ka: 'ვთანხმდებით, რას უნდა მიაღწიოს ვებსაიტმა, ვქმნით სწორ მიმართულებას და ვუშვებთ მომხმარებლისთვის თქვენთან დაკავშირების მკაფიო გზით.', ru: 'Определяем задачу сайта, создаём правильное направление и запускаем его с понятным путём клиента к обращению.' },
  'Ready for more enquiries?': { ka: 'მზად ხართ მეტი მომართვისთვის?', ru: 'Готовы получать больше обращений?' }, 'Put your business': { ka: 'აჩვენეთ თქვენი ბიზნესი', ru: 'Покажите свой бизнес' }, 'in front of more customers.': { ka: 'უფრო მეტ მომხმარებელს.', ru: 'большему числу клиентов.' }, 'Tell us about your business. We’ll recommend the clearest way to help new customers find you and get in touch.': { ka: 'გვიამბეთ თქვენი ბიზნესის შესახებ. გირჩევთ ყველაზე მკაფიო გზას, რომ ახალმა მომხმარებლებმა გიპოვონ და დაგიკავშირდნენ.', ru: 'Расскажите о своём бизнесе. Мы предложим понятный способ помочь новым клиентам найти вас и связаться с вами.' },
  'Ready to get found?': { ka: 'მზად ხართ, რომ გიპოვონ?', ru: 'Готовы стать заметнее?' }, 'Turn more searches': { ka: 'მეტი ძიება აქციეთ', ru: 'Превратите больше поисков' }, 'into enquiries.': { ka: 'რეალურ მომართვებად.', ru: 'в реальные обращения.' },
  'Look like the right choice.': { ka: 'გამოიყურებოდეთ სწორ არჩევანად.', ru: 'Выглядите правильным выбором.' }, 'A distinctive website that makes your business clear, credible and easy to choose.': { ka: 'გამორჩეული ვებსაიტი, რომელიც თქვენს ბიზნესს გასაგებად, სანდოდ და მარტივად ასარჩევად წარმოაჩენს.', ru: 'Выразительный сайт, который делает ваш бизнес понятным, убедительным и лёгким для выбора.' },
  'Be there when customers search.': { ka: 'იყავით იქ, სადაც მომხმარებელი ეძებს.', ru: 'Будьте там, где ищут клиенты.' }, 'Fast, search-ready pages that help the right people discover your business online.': { ka: 'სწრაფი, ძიებისთვის მომზადებული გვერდები, რომლებიც სწორ ადამიანებს თქვენი ბიზნესის ონლაინ აღმოჩენაში ეხმარება.', ru: 'Быстрые страницы, готовые к поиску, помогают нужным людям находить ваш бизнес онлайн.' },
  'Make the next step obvious.': { ka: 'შემდეგი ნაბიჯი აშკარა გახადეთ.', ru: 'Сделайте следующий шаг очевидным.' }, 'Clear contact actions and straightforward forms turn more interested visitors into real conversations.': { ka: 'მკაფიო საკონტაქტო მოქმედებები და მარტივი ფორმები მეტ დაინტერესებულ ვიზიტორს რეალურ საუბრად აქცევს.', ru: 'Понятные контакты и простые формы превращают больше заинтересованных посетителей в реальные разговоры.' },
  'What should your website do?': { ka: 'რას უნდა აკეთებდეს თქვენი ვებსაიტი?', ru: 'Что должен делать ваш сайт?' }, 'Choose the outcome.': { ka: 'აირჩიეთ შედეგი.', ru: 'Выберите результат.' }, 'You bring the goal. We’ll handle the design, technology and details.': { ka: 'თქვენ გვითხარით მიზანი. დიზაინს, ტექნოლოგიასა და დეტალებს ჩვენ მივხედავთ.', ru: 'Вы ставите цель. Мы берём на себя дизайн, технологии и детали.' },
  'Make a strong first impression—and an easy choice.': { ka: 'შექმენით ძლიერი პირველი შთაბეჭდილება და გაამარტივეთ არჩევანი.', ru: 'Произведите сильное первое впечатление и упростите выбор.' }, 'Custom design': { ka: 'ინდივიდუალური დიზაინი', ru: 'Индивидуальный дизайн' }, 'Mobile-first': { ka: 'მობილურზე მორგებული', ru: 'Сначала для мобильных' },
  'Get found on Google.': { ka: 'გიპოვონ Google-ში.', ru: 'Пусть вас находят в Google.' }, 'Help the right customers discover your business.': { ka: 'დაეხმარეთ სწორ მომხმარებლებს აღმოაჩინონ თქვენი ბიზნესი.', ru: 'Помогите нужным клиентам найти ваш бизнес.' }, 'Search-ready': { ka: 'ძიებისთვის მზად', ru: 'Готово к поиску' }, 'Fast loading': { ka: 'სწრაფი ჩატვირთვა', ru: 'Быстрая загрузка' },
  'Turn visits into enquiries.': { ka: 'ვიზიტები აქციეთ მომართვებად.', ru: 'Превращайте посещения в заявки.' }, 'Make it effortless to call, message or request a quote.': { ka: 'გაამარტივეთ დარეკვა, მოწერა ან შეთავაზების მოთხოვნა.', ru: 'Упростите звонок, сообщение или запрос цены.' }, 'Clear actions': { ka: 'მკაფიო მოქმედებები', ru: 'Понятные действия' }, 'Simple forms': { ka: 'მარტივი ფორმები', ru: 'Простые формы' },
  'Make business easier.': { ka: 'გაამარტივეთ ბიზნესი.', ru: 'Упростите работу бизнеса.' }, 'Let customers book, browse or order without friction.': { ka: 'მიეცით მომხმარებლებს დაჯავშნის, დათვალიერებისა და შეკვეთის მარტივი გზა.', ru: 'Позвольте клиентам легко бронировать, выбирать и заказывать.' }, 'Bookings & menus': { ka: 'ჯავშნები და მენიუები', ru: 'Бронирование и меню' }, 'Useful integrations': { ka: 'სასარგებლო ინტეგრაციები', ru: 'Полезные интеграции' },
  'Simplify how work gets done.': { ka: 'გაამარტივეთ სამუშაო პროცესი.', ru: 'Упростите рабочие процессы.' }, 'Useful tools built around your customers or team.': { ka: 'სასარგებლო ხელსაწყოები თქვენი მომხმარებლებისა და გუნდის საჭიროებებზე.', ru: 'Полезные инструменты под задачи клиентов или команды.' }, 'Portals & dashboards': { ka: 'პორტალები და დაფები', ru: 'Порталы и панели' },
  'Why a website?': { ka: 'რატომ ვებსაიტი?', ru: 'Зачем нужен сайт?' }, 'People are already looking.': { ka: 'ხალხი უკვე ეძებს.', ru: 'Люди уже ищут.' }, 'Make sure they find you.': { ka: 'დარწმუნდით, რომ თქვენ გიპოვიან.', ru: 'Сделайте так, чтобы нашли вас.' }, 'Without a strong website, the next customer may choose the business they can understand and trust online.': { ka: 'ძლიერი ვებსაიტის გარეშე, შემდეგმა მომხმარებელმა შეიძლება აირჩიოს ბიზნესი, რომელიც ონლაინ უფრო გასაგები და სანდოა.', ru: 'Без сильного сайта следующий клиент может выбрать бизнес, который понятнее и убедительнее выглядит онлайн.' },
  'Be found beyond social media.': { ka: 'გიპოვონ სოციალური ქსელების გარეთაც.', ru: 'Вас найдут не только в соцсетях.' }, 'Show up when people search—not only when they scroll.': { ka: 'გამოჩნდით მაშინ, როცა ადამიანები ეძებენ და არა მხოლოდ მაშინ, როცა სქროლავენ.', ru: 'Появляйтесь, когда люди ищут, а не только листают ленту.' }, 'Look established.': { ka: 'გამოიყურებოდეთ სანდოდ.', ru: 'Выглядите солидно.' }, 'Give customers one clear place to understand and trust your business.': { ka: 'მიეცით მომხმარებლებს ერთი მკაფიო სივრცე თქვენი ბიზნესის გასაცნობად და ნდობისთვის.', ru: 'Дайте клиентам одно понятное место, где можно узнать ваш бизнес и довериться ему.' }, 'Turn interest into action.': { ka: 'ინტერესი აქციეთ მოქმედებად.', ru: 'Превратите интерес в действие.' }, 'Make calling, messaging and booking the obvious next step.': { ka: 'დარეკვა, მოწერა და დაჯავშნა გახადეთ აშკარა შემდეგ ნაბიჯად.', ru: 'Сделайте звонок, сообщение или бронирование очевидным следующим шагом.' },
  'Premium business website displayed on a laptop': { ka: 'ლეპტოპზე ნაჩვენები პრემიუმ ბიზნეს ვებსაიტი', ru: 'Премиальный бизнес-сайт на экране ноутбука' }, 'Google search results viewed through a magnifying glass': { ka: 'გამადიდებელი შუშით ნაჩვენები Google-ის ძიების შედეგები', ru: 'Результаты Google под увеличительным стеклом' }, 'New customer enquiry displayed on a smartphone': { ka: 'სმარტფონზე ნაჩვენები ახალი მომხმარებლის შეტყობინება', ru: 'Новое обращение клиента на смартфоне' }, 'Online booking calendar displayed on a tablet': { ka: 'ტაბლეტზე ნაჩვენები ონლაინ დაჯავშნის კალენდარი', ru: 'Календарь онлайн-бронирования на планшете' }, 'Custom business dashboard displayed on a desktop monitor': { ka: 'დესკტოპ მონიტორზე ნაჩვენები ბიზნეს დაფა', ru: 'Бизнес-панель на настольном мониторе' },
}

type I18nValue = { language: Language; setLanguage: (language: Language) => void; t: (source: string) => string }
const I18nContext = createContext<I18nValue | null>(null)

export function languageFromPath(pathname: string): Language | null {
  const value = pathname.split('/')[1]
  return value === 'en' || value === 'ka' || value === 'ru' ? value : null
}

function preferredLanguage(): Language {
  if (typeof window === 'undefined') return 'en'
  try { const saved = localStorage.getItem('salyior-language'); if (saved === 'en' || saved === 'ka' || saved === 'ru') return saved } catch { /* private mode */ }
  const preferred = navigator.languages?.length ? navigator.languages : [navigator.language]
  if (preferred.some(value => value.toLowerCase().startsWith('ka'))) return 'ka'
  if (preferred.some(value => value.toLowerCase().startsWith('ru'))) return 'ru'
  return 'en'
}

export function localizePath(to: string, language: Language) {
  if (!to.startsWith('/') || to.startsWith('//')) return to
  const match = to.match(/^\/(en|ka|ru)(?=\/|\?|#|$)/)
  return match ? to.replace(/^\/(en|ka|ru)/, `/${language}`) : `/${language}${to === '/' ? '' : to}`
}

export function I18nProvider({ children }: PropsWithChildren) {
  const location = useLocation()
  const navigate = useNavigate()
  const pathLanguage = languageFromPath(location.pathname)
  const [language, setCurrent] = useState<Language>(() => pathLanguage || preferredLanguage())

  useEffect(() => {
    if (pathLanguage) { setCurrent(pathLanguage); document.documentElement.lang = pathLanguage; return }
    document.documentElement.lang = language
    navigate(localizePath(`${location.pathname}${location.search}${location.hash}`, language), { replace: true })
  }, [pathLanguage, language, location.pathname, location.search, location.hash, navigate])

  const setLanguage = useCallback((next: Language) => {
    setCurrent(next)
    try { localStorage.setItem('salyior-language', next) } catch { /* selection still works */ }
    navigate(localizePath(`${location.pathname}${location.search}${location.hash}`, next))
  }, [location.pathname, location.search, location.hash, navigate])

  const t = useCallback((source: string) => copy[source]?.[language] || source, [language])
  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export function useI18n() {
  const value = useContext(I18nContext)
  if (!value) throw new Error('useI18n must be used inside I18nProvider')
  return value
}
